//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// GymManagementSystem.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GYMMANAGEMENTSYSTEM_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SELECT               130
#define IDD_DIALOG_SEL_1                133
#define IDD_DIALOG_SEL_2                135
#define IDD_DIALOG_SEL_3                136
#define IDD_DIALOG_SEL_4                137
#define IDD_DIALOG_SEL_5                138
#define IDD_DIALOG_SCHEMA               161
#define IDD_DIALOG_INSERT               163
#define IDD_DIALOG_UPDATE               165
#define IDD_DIALOG_UPD_1                166
#define IDD_DIALOG_UPD_2                167
#define IDD_DIALOG_UPD_3                168
#define IDD_DIALOG_UPD_4                169
#define IDD_DIALOG_DELETE               175
#define IDD_DIALOG_DEL_1                176
#define IDD_DIALOG_DEL_2                177
#define IDD_DIALOG_DEL_3                178
#define IDD_DIALOG_DEL_4                179
#define IDD_DIALOG_CUSTOM               185
#define IDD_DIALOG_CUS_1                186
#define IDD_DIALOG_CUS_2                187
#define IDD_DIALOG_CUS_3                188
#define IDD_DIALOG_CUS_4                189
#define IDD_DIALOG_CUS_0                190
#define IDD_DIALOG_CUS_5                197
#define IDC_BUTTON_SCHEMA               1001
#define IDC_BUTTON_SELECT               1002
#define IDC_BUTTON_INSERT               1003
#define IDC_BUTTON_CUSTOM               1004
#define IDC_BUTTON_UPDATE               1005
#define IDC_BUTTON_DELETE               1006
#define IDC_TAB1                        1007
#define IDC_LIST_SEL_1                  1018
#define IDC_BUTTON1                     1019
#define IDC_LIST_SEL_2                  1020
#define IDC_EDIT_SEL_2                  1021
#define IDC_BUTTON_SEL_2                1022
#define IDC_STATIC_SEL_3                1023
#define IDC_LIST_SEL_3                  1025
#define IDC_BUTTON_SEL_3                1026
#define IDC_COMBO1                      1029
#define IDC_LIST_SCHEMA                 1031
#define IDC_RADIO_TRAINER               1033
#define IDC_RADIO_PROGRAM               1034
#define IDC_RADIO_FITNESS_EQUIPMENT     1035
#define IDC_RADIO_PRODUCT               1036
#define IDC_RADIO_MEMBER                1037
#define IDC_EDIT_AT_1                   1038
#define IDC_STATIC_AT_NAME1             1039
#define IDC_EDIT_AT_2                   1040
#define IDC_EDIT_AT_3                   1041
#define IDC_EDIT_AT_4                   1042
#define IDC_EDIT_AT_5                   1043
#define IDC_EDIT_AT_6                   1044
#define IDC_EDIT_AT_7                   1045
#define IDC_STATIC_AT_NAME2             1046
#define IDC_STATIC_AT_NAME3             1047
#define IDC_STATIC_AT_NAME4             1048
#define IDC_STATIC_AT_NAME5             1049
#define IDC_STATIC_AT_NAME6             1050
#define IDC_STATIC_AT_NAME7             1051
#define IDC_TAB_UPDATE                  1052
#define IDC_LIST_UPD_1                  1053
#define IDC_EDIT_SERIAL                 1054
#define IDC_EDIT_CONTENT                1055
#define IDC_DATETIMEPICKER2             1057
#define IDC_BUTTON_UPD1                 1058
#define IDC_LIST_UPD_2                  1059
#define IDC_STATIC_UPD_2                1060
#define IDC_TAB_DEL                     1062
#define IDC_LIST_DEL_1                  1063
#define IDC_STATIC_DEL1                 1064
#define IDC_BUTTON_DEL1                 1065
#define IDC_EDIT_MEMBER_NUMBER          1066
#define IDC_STATIC_DEL2                 1068
#define IDC_EDIT_MEMBER_NUMBER2         1069
#define IDC_STATIC_2                    1070
#define IDC_BUTTON_DEL2                 1071
#define IDC_LIST2                       1072
#define IDC_BUTTON_CUS_1_CREATE         1075
#define IDC_EDIT_PROGRAM                1076
#define IDC_BUTTON_CUS_2                1076
#define IDC_BUTTON_QUERY                1078
#define IDC_LIST_CUS_0                  1079
#define IDC_LIST_SEL_4                  1080
#define IDC_BUTTON_SEL_4                1081
#define IDC_LIST_UPD_3                  1082
#define IDC_LIST1_UPD_4                 1083
#define IDC_BUTTON_UPD_4                1084
#define IDC_LIST1_SEL_5                 1085
#define IDC_EDIT1_SEL_5                 1086
#define IDC_BUTTON_UPD_3                1087
#define IDC_LIST1_LOCKER                1089
#define IDC_EDIT_LOCKER                 1090
#define IDC_LIST1_DEL_3                 1091
#define IDC_LIST1_DEL_3_PH              1092
#define IDC_BUTTON_DEL_3                1093
#define IDC_EDIT1                       1094
#define IDC_EDIT2_POGRAM_NO             1095
#define IDC_BUTTON1_LOAD                1096
#define IDC_EDIT_QUERY                  1097
#define IDC_EDIT_PROGRAM_NO             1098
#define IDC_EDIT_MEMBER_NO              1099
#define IDC_BUTTON_CUS_EXECUTE          1100
#define IDC_EDIT_PRODUCT_NO             1101
#define IDC_EDIT_PRODUCT_NO2            1102
#define IDC_LIST_DEL_4                  1103
#define IDC_EDIT_SERIAL_NO              1104
#define IDC_LIST1                       1105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
